# Ethereum BIP39 Seed Phrase Recovery Configuration

# Mnemonic length (12 or 24 words)
mnemonic_length = 12

# Wallet type
wallet_type = "ethereum"

[ethereum]
# Target Ethereum address to recover
target_address = "0x053ee470c62f02cD5bE08A50296b3cBFe171617C"

# Derivation path (Metamask standard)
derivation_path = "m/44'/60'/0'/0/2"

# Passphrase (empty for most wallets)
passphrase = ""

# Word constraints - each position with possible words
[[word_constraints]]
position = 0
words = ["income", "inch", "inner", "input", "include"]

[[word_constraints]]
position = 1
words = ["banner", "barrel", "barely", "bamboo"]

[[word_constraints]]
position = 2
words = ["title", "tiny", "tissue", "tiger", "timber"]

[[word_constraints]]
position = 3
words = ["cushion", "cup", "curtain", "culture"]

[[word_constraints]]
position = 4
words = ["butter", "busy", "bubble", "buyer"]

[[word_constraints]]
position = 5
words = ["rapid", "ramp", "rare", "random", "ranch"]

[[word_constraints]]
position = 6
words = ["student", "stuff", "studio", "stumble"]

[[word_constraints]]
position = 7
words = ["across", "acquire", "accuse", "actress", "acid"]

[[word_constraints]]
position = 8
words = ["ticket", "timber", "tide", "tiger"]

[[word_constraints]]
position = 9
words = ["excess", "exercise", "exile", "exit"]

[[word_constraints]]
position = 10
words = ["theory", "theme", "then", "thesis", "therapy"]

[[word_constraints]]
position = 11
words = ["decision", "decline", "decorate", "decode"]
